### ISSUE TITLE
ZigBee Groups - Is it possible to configure and control groups?

### ISSUE THREAD

**Issue by kiall** [zigpy/bellows#111]
Hi,

I've got a bunch of downlights I'm controlling with Home Assistant+zha, and I've noticed a reasonably large delay between the first and last light when toggling a group of 8 lights. Looking at the HA logs, the first to last light is toggled within 0.6 seconds, however that's a noticeable period of time (and I believe the lights are actually taking a little longer, to actually receive all the commands)

Poking around the zigpy and bellows code, I've spotted some membership related code, but don't seem to be able to use it (likely my own fault ;))

I'm hoping this is something supported to configure, at least the ZigBee pieces of it?

My initial attempts to even list membership seem to fail, though I'm aware listing/creating groups is only step 1 - and I'll need likely to extend `zha` to recognise the groups:

    $ bellows -d /dev/ttyUSB0 -b 57600 zcl 00:17:88:01:02:9f:7a:6d 11 4 command get_membership 1
    Traceback (most recent call last):
      File "/home/kiall/opt/hass/homeassistant/bin/bellows", line 11, in <module>
        sys.exit(main())
      File "/home/kiall/opt/hass/homeassistant/lib/python3.5/site-packages/click/core.py", line 722, in __call__
        return self.main(*args, **kwargs)
      File "/home/kiall/opt/hass/homeassistant/lib/python3.5/site-packages/click/core.py", line 697, in main
        rv = self.invoke(ctx)
      File "/home/kiall/opt/hass/homeassistant/lib/python3.5/site-packages/click/core.py", line 1066, in invoke
        return _process_result(sub_ctx.command.invoke(sub_ctx))
      File "/home/kiall/opt/hass/homeassistant/lib/python3.5/site-packages/click/core.py", line 1066, in invoke
        return _process_result(sub_ctx.command.invoke(sub_ctx))
      File "/home/kiall/opt/hass/homeassistant/lib/python3.5/site-packages/click/core.py", line 895, in invoke
        return ctx.invoke(self.callback, **ctx.params)
      File "/home/kiall/opt/hass/homeassistant/lib/python3.5/site-packages/click/core.py", line 535, in invoke
        return callback(*args, **kwargs)
      File "/home/kiall/opt/hass/homeassistant/lib/python3.5/site-packages/click/decorators.py", line 17, in new_func
        return f(get_current_context(), *args, **kwargs)
      File "/home/kiall/opt/hass/homeassistant/lib/python3.5/site-packages/bellows/cli/util.py", line 72, in inner
        loop.run_until_complete(async_inner(*args, **kwargs))
      File "/home/kiall/.pyenv/versions/3.5.5/lib/python3.5/asyncio/base_events.py", line 467, in run_until_complete
        return future.result()
      File "/home/kiall/.pyenv/versions/3.5.5/lib/python3.5/asyncio/futures.py", line 294, in result
        raise self._exception
      File "/home/kiall/.pyenv/versions/3.5.5/lib/python3.5/asyncio/tasks.py", line 240, in _step
        result = coro.send(None)
      File "/home/kiall/opt/hass/homeassistant/lib/python3.5/site-packages/bellows/cli/util.py", line 59, in async_inner
        yield from f(ctx, *args, **kwargs)
      File "/home/kiall/opt/hass/homeassistant/lib/python3.5/site-packages/bellows/cli/application.py", line 310, in command
        v = yield from getattr(cluster, command)(*parameters, manufacturer=manufacturer)
      File "/home/kiall/opt/hass/homeassistant/lib/python3.5/site-packages/zigpy/zcl/__init__.py", line 300, in command
        return self.request(False, command, schema, *args, manufacturer=manufacturer, expect_reply=expect_reply)
      File "/home/kiall/opt/hass/homeassistant/lib/python3.5/site-packages/zigpy/util.py", line 73, in wrapper
        return func(*args, **kwargs)
      File "/home/kiall/opt/hass/homeassistant/lib/python3.5/site-packages/zigpy/zcl/__init__.py", line 134, in request
        data += t.serialize(args, schema)
      File "/home/kiall/opt/hass/homeassistant/lib/python3.5/site-packages/zigpy/types/__init__.py", line 15, in serialize
        return b''.join(t(v).serialize() for t, v in zip(schema, data))
      File "/home/kiall/opt/hass/homeassistant/lib/python3.5/site-packages/zigpy/types/__init__.py", line 15, in <genexpr>
        return b''.join(t(v).serialize() for t, v in zip(schema, data))
      File "/home/kiall/opt/hass/homeassistant/lib/python3.5/site-packages/zigpy/types/basic.py", line 146, in serialize
        data = super().serialize()
      File "/home/kiall/opt/hass/homeassistant/lib/python3.5/site-packages/zigpy/types/basic.py", line 130, in serialize
        return b''.join([i.serialize() for i in self])
      File "/home/kiall/opt/hass/homeassistant/lib/python3.5/site-packages/zigpy/types/basic.py", line 130, in <listcomp>
        return b''.join([i.serialize() for i in self])
    AttributeError: 'str' object has no attribute 'serialize'

Thanks!

**Comment by Adminiuga** [comment]
I was thinking about the same, but my idea was to use groups to "bind" a zigbee switch directly to a group, so I could control the lights even if the HA is down. 
I cannot create group. I suspect it is because of the way CLI parameters are passed into zigbee command parameters. I'm getting this error when trying to create a group
```(rcl-hass) lex@NUCa:~/.homeassistant$ bellows zcl f0:d1:b8:00:00:00:ac:4b 1 4 command add 8192 ' '
Traceback (most recent call last):
  File "/home/lex/rcl-hass/bin/bellows", line 11, in <module>
    sys.exit(main())
  File "/home/lex/rcl-hass/lib/python3.5/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/lex/rcl-hass/lib/python3.5/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/lex/rcl-hass/lib/python3.5/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/lex/rcl-hass/lib/python3.5/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/lex/rcl-hass/lib/python3.5/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/lex/rcl-hass/lib/python3.5/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/lex/rcl-hass/lib/python3.5/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/lex/rcl-hass/lib/python3.5/site-packages/bellows/cli/util.py", line 72, in inner
    loop.run_until_complete(async_inner(*args, **kwargs))
  File "/usr/lib/python3.5/asyncio/base_events.py", line 466, in run_until_complete
    return future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 293, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/home/lex/rcl-hass/lib/python3.5/site-packages/bellows/cli/util.py", line 59, in async_inner
    yield from f(ctx, *args, **kwargs)
  File "/home/lex/rcl-hass/lib/python3.5/site-packages/bellows/cli/application.py", line 310, in command
    v = yield from getattr(cluster, command)(*parameters, manufacturer=manufacturer)
  File "/home/lex/rcl-hass/lib/python3.5/site-packages/zigpy/zcl/__init__.py", line 300, in command
    return self.request(False, command, schema, *args, manufacturer=manufacturer, expect_reply=expect_reply)
  File "/home/lex/rcl-hass/lib/python3.5/site-packages/zigpy/util.py", line 73, in wrapper
    return func(*args, **kwargs)
  File "/home/lex/rcl-hass/lib/python3.5/site-packages/zigpy/zcl/__init__.py", line 134, in request
    data += t.serialize(args, schema)
  File "/home/lex/rcl-hass/lib/python3.5/site-packages/zigpy/types/__init__.py", line 15, in serialize
    return b''.join(t(v).serialize() for t, v in zip(schema, data))
  File "/home/lex/rcl-hass/lib/python3.5/site-packages/zigpy/types/__init__.py", line 15, in <genexpr>
    return b''.join(t(v).serialize() for t, v in zip(schema, data))
TypeError: string argument without an encoding```

**Comment by kabturek** [comment]
I'm interested in this as well - it's the only thing that stops me from replacing some manual switches with a wireless switch + zigbee bulb.

**Comment by puddly** [comment]
I'm able to add lights to groups using that cluster command:

    await light.endpoints[0x0001].groups.add(0x1234, b'My Group')

Communicating with a group of lights is more difficult, though. You basically need to make a subclass of `zigpy.application.ControllerApplication.request` that uses `self._ezsp.sendMulticast` instead of `self._ezsp.sendUnicast` and sets `aps_frame.groupId = t.uint16_t(0x1234)`. I'm not familiar enough with Zigbee to get a usable reply to that command but at least I can get groups of lights to turn on and off simultaneously.

I suspect you'll need to write a `Device` subclass that wraps a list of of other `Device`s to get this to work well.

**Comment by Adminiuga** [comment]
Yep, this area needs an improvement. Probably should do generic stuff in `zigpy` and leave `multicast` implementation specific to the radios.
And we need to "subscribe" to groups as well if you want to receive messages sent by the groups. 

BTW, you could configure bind with group addressing on the remotes and control your groups from the remotes. I'm using this code snippet
```
async def bind_group(src_dev, group_id):
    from zigpy.zdo.types import MultiAddress
    from zigpy import types as t

    zdo = src_dev.zdo
    src_cls = [6, 8, 768]

    # find src ep_id
    dst_addr = MultiAddress()
    dst_addr.addrmode = t.uint8_t(1)
    dst_addr.nwk = t.uint16_t(group_id)
    for src_cluster in src_cls:
        src_epid = None
        for ep_id, ep in src_dev.endpoints.items():
            if ep_id == 0:
                continue
            if src_cluster in ep.out_clusters:
                src_epid = ep_id
                break
        if not src_epid:
            LOGGER.debug("0x%04x: skipping %s cluster as non present",
                         src_dev.nwk, src_cluster)
            continue
        LOGGER.debug("0x%04x: binding %s, ep: %s, cluster: %s",
                     src_dev.nwk, str(src_dev.ieee), src_epid, src_cluster)
        res = await zdo.request(0x0021, src_dev.ieee, src_epid, src_cluster,
                                dst_addr)
        LOGGER.debug("0x%04x: binding group 0x%04x: %s",
                     src_dev.nwk, group_id, res)
```

**Comment by Adminiuga** [comment]
Home assistant supports groups in version 0.110.x, closing this one.
