### ISSUE TITLE
Zha failing on startup - some devices not available

### ISSUE THREAD

**Issue by ryanwinter** [zigpy/bellows#118]
I have started seeing the following exception when I start HA. I get this error twice, and also I have two Smartthing Outlets that fail to show up. Not sure if this is related.

```
Error while setting up platform zha
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/homeassistant/helpers/entity_platform.py", line 129, in _async_setup_platform
    SLOW_SETUP_MAX_WAIT, loop=hass.loop)
  File "/usr/local/lib/python3.6/asyncio/tasks.py", line 358, in wait_for
    return fut.result()
  File "/usr/local/lib/python3.6/site-packages/homeassistant/components/switch/zha.py", line 27, in async_setup_platform
    await cluster.bind()
  File "/mnt/homeassistant/hass/deps/lib/python3.6/site-packages/bellows/zigbee/application.py", line 248, in request
    raise DeliveryError("Message send failure %s" % (v[0], ))
zigpy.exceptions.DeliveryError: Message send failure EmberStatus.MAX_MESSAGE_LIMIT_REACHED
```

**Comment by ryanwinter** [comment]
After installing HA 0.69 and restarting, the missing devices are back and the error messages are gone.

**Comment by xerootg** [comment]
I have this same symptom in 0.72.1. I have several KoF devices that 'take turns' showing up in HA. Any leads? I'd love to contribute.

**Comment by ryanwinter** [comment]
Smartthings outlets are no longer available after reboot. When I zha permit add them, they are available until the reboot.

Weirdly, the power component of the outlet is available at all times.

**Comment by WhiteNoseThunderPants** [comment]
I am having similar issues with the KoF lights, the fan's are showing up, and peanut plugs, the sensors show up. I'm not sure if my logs will help, but I am on 0.77.3.

Here are my relevant logs on default logging:

`2018-09-05 20:59:19 ERROR (MainThread) [homeassistant.components.switch] Error while setting up platform zha
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.6/site-packages/homeassistant/helpers/entity_platform.py", line 128, in _async_setup_platform
    SLOW_SETUP_MAX_WAIT, loop=hass.loop)
  File "/usr/lib/python3.6/asyncio/tasks.py", line 358, in wait_for
    return fut.result()
  File "/srv/homeassistant/lib/python3.6/site-packages/homeassistant/components/switch/zha.py", line 27, in async_setup_platform
    await cluster.bind()
  File "/srv/homeassistant/lib/python3.6/site-packages/zigpy/device.py", line 89, in request
    expect_reply=expect_reply,
  File "/srv/homeassistant/lib/python3.6/site-packages/bellows/zigbee/application.py", line 238, in request
    raise DeliveryError("Message send failure %s" % (v[0], ))
zigpy.exceptions.DeliveryError: Message send failure EmberStatus.MAX_MESSAGE_LIMIT_REACHED
2018-09-05 20:59:19 ERROR (MainThread) [homeassistant.components.switch] Error while setting up platform zha
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.6/site-packages/homeassistant/helpers/entity_platform.py", line 128, in _async_setup_platform
    SLOW_SETUP_MAX_WAIT, loop=hass.loop)
  File "/usr/lib/python3.6/asyncio/tasks.py", line 358, in wait_for
    return fut.result()
  File "/srv/homeassistant/lib/python3.6/site-packages/homeassistant/components/switch/zha.py", line 28, in async_setup_platform
    await cluster.configure_reporting(0, 0, 600, 1,)
  File "/srv/homeassistant/lib/python3.6/site-packages/zigpy/device.py", line 89, in request
    expect_reply=expect_reply,
  File "/srv/homeassistant/lib/python3.6/site-packages/bellows/zigbee/application.py", line 238, in request
    raise DeliveryError("Message send failure %s" % (v[0], ))
zigpy.exceptions.DeliveryError: Message send failure EmberStatus.MAX_MESSAGE_LIMIT_REACHED
2018-09-05 20:59:22 ERROR (MainThread) [homeassistant.components.switch] Error while setting up platform zha
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.6/site-packages/homeassistant/helpers/entity_platform.py", line 128, in _async_setup_platform
    SLOW_SETUP_MAX_WAIT, loop=hass.loop)
  File "/usr/lib/python3.6/asyncio/tasks.py", line 358, in wait_for
    return fut.result()
  File "/srv/homeassistant/lib/python3.6/site-packages/homeassistant/components/switch/zha.py", line 27, in async_setup_platform
    await cluster.bind()
  File "/srv/homeassistant/lib/python3.6/site-packages/zigpy/device.py", line 89, in request
    expect_reply=expect_reply,
  File "/srv/homeassistant/lib/python3.6/site-packages/bellows/zigbee/application.py", line 241, in request
    v = await send_fut
zigpy.exceptions.DeliveryError: Message send failure: EmberStatus.DELIVERY_FAILED
2018-09-05 20:59:22 ERROR (MainThread) [homeassistant.components.switch] Error while setting up platform zha
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.6/site-packages/homeassistant/helpers/entity_platform.py", line 128, in _async_setup_platform
    SLOW_SETUP_MAX_WAIT, loop=hass.loop)
  File "/usr/lib/python3.6/asyncio/tasks.py", line 358, in wait_for
    return fut.result()
  File "/srv/homeassistant/lib/python3.6/site-packages/homeassistant/components/switch/zha.py", line 27, in async_setup_platform
    await cluster.bind()
  File "/srv/homeassistant/lib/python3.6/site-packages/zigpy/device.py", line 89, in request
    expect_reply=expect_reply,
  File "/srv/homeassistant/lib/python3.6/site-packages/bellows/zigbee/application.py", line 241, in request
    v = await send_fut
zigpy.exceptions.DeliveryError: Message send failure: EmberStatus.DELIVERY_FAILED
2018-09-05 20:59:22 ERROR (MainThread) [homeassistant.components.switch] Error while setting up platform zha
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.6/site-packages/homeassistant/helpers/entity_platform.py", line 128, in _async_setup_platform
    SLOW_SETUP_MAX_WAIT, loop=hass.loop)
  File "/usr/lib/python3.6/asyncio/tasks.py", line 358, in wait_for
    return fut.result()
  File "/srv/homeassistant/lib/python3.6/site-packages/homeassistant/components/switch/zha.py", line 27, in async_setup_platform
    await cluster.bind()
  File "/srv/homeassistant/lib/python3.6/site-packages/zigpy/device.py", line 89, in request
    expect_reply=expect_reply,
  File "/srv/homeassistant/lib/python3.6/site-packages/bellows/zigbee/application.py", line 241, in request
    v = await send_fut
zigpy.exceptions.DeliveryError: Message send failure: EmberStatus.DELIVERY_FAILED
2018-09-05 20:59:23 WARNING (MainThread) [bellows.zigbee.application] Unexpected response TSN=16 command=1 args=[[<ReadAttributeRecord attrid=1291 status=0 value=0>]]
2018-09-05 20:59:23 WARNING (MainThread) [bellows.zigbee.application] Unexpected response TSN=16 command=1 args=[[<ReadAttributeRecord attrid=1291 status=0 value=0>]]`

**Comment by ryanwinter** [comment]
Connecting it the two await calls in the switch zha.py fixes the problem. I'm unsure why these calls were added it what they do. I wonder if it's possible to just wrap these calls and catch the exception and then just continue.

**Comment by WhiteNoseThunderPants** [comment]
@ryanwinter Are you referencing this [PR](https://github.com/home-assistant/home-assistant/pull/16382)? I am not a programmer by any means, but fi I understand the diff on the PR, all you removed was the command await from two lines? What is the await command supposed to be doing? I'm assuming you have not had any unfrotunate consequences from this?

**Comment by WhiteNoseThunderPants** [comment]
@ryanwinter I went ahead and made the changes that you submitted with your PR. As soon as I restarted HASS, the switches that disappeared did come back. I was not even able to get them back with a reboot previously. I do not see the error messages anymore. I'm going to try this for a few days and see what happens.

Have you tried the zha_new component and the fork of zigpy/bellows? I'm curious if it has the same problems.

**Comment by ryanwinter** [comment]
Yes, that PR was my attempt to fix the problem without actually understand the change I was making.

Those two calls were added in an older PR to update the status of the device at startup I believe. It worked at the time, however since then those calls now throw an exception. The easiest fix would be to catch the exception in HA and just continue which maintain the existing logic, but make it more resilient. Longer term would be to understand why the calls are failing now and fix that.

I haven't seen the zha_new component, and which bellows fork are you talking about?

BTW, there is a new release of bellows and zigpy this week, I'll probably check those versions to see if the problem still exists.

**Comment by WhiteNoseThunderPants** [comment]
I did see the update to bellows and zigpy, but they unfortunately did not fix the problem for me.

The zha_new custom component is [here](https://github.com/Yoda-x/ha-zha-new) and the same author has a fork of [zigpy](https://github.com/Yoda-x/zigpy) and [bellows](https://github.com/Yoda-x/bellows) that the component requires.

**Comment by ryanwinter** [comment]
I wouldn't say expected, but the reason you weren't seeing them before is because the device was never setup correctly in HA so these were likely hidden.

**Comment by ryanwinter** [comment]
I created a new PR in HA which basically catches the exception and continues.
https://github.com/home-assistant/home-assistant/pull/16474

**Comment by WhiteNoseThunderPants** [comment]
@ryanwinter Thank you so much for your help and the time you have put into this. I will watch to see if they are willing to merge this one.

**Comment by Adminiuga** [comment]
Please try with the latest HA version and reopen if the issue still persists.
