### ISSUE TITLE
CLI async uart timeout errors

### ISSUE THREAD

**Issue by jeffleary00** [zigpy/bellows#393]
Hi,

Currently using the EleLabs Zigbee Raspberry Pi shield (RPi 4) for a custom project (Not using HomeAssistant or OpenHab)

The hardware device responds to firmware updates, and other basic interface commands. But bellows CLI is giving asyncio uart timeout errors on every command I try.
Advice on what may be wrong? Version conflicts?

**Python Version**
```
pi@raspberrypi:~ $ python3 --version
Python 3.7.3
```

**Raspberry Pi OS Details**
```
pi@raspberrypi:~ $ cat /etc/os-release 
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
```

**Installed versions of bellows and zigpy**
```
pi@raspberrypi:~ $ pip3 show bellows zigpy
Name: bellows
Version: 0.21.0
Summary: Library implementing EZSP
Home-page: http://github.com/zigpy/bellows
Author: Russell Cloran
Author-email: rcloran@gmail.com
License: GPL-3.0
Location: /home/pi/ve/lib/python3.7/site-packages
Requires: voluptuous, zigpy, click-log, pure-pcapy3, pyserial-asyncio, Click
Required-by: 
---
Name: zigpy
Version: 0.32.0
Summary: Library implementing a ZigBee stack
Home-page: https://github.com/zigpy/zigpy
Author: Russell Cloran
Author-email: rcloran@gmail.com
License: GPL-3.0
Location: /home/pi/ve/lib/python3.7/site-packages
Requires: voluptuous, pycryptodome, crccheck, aiohttp, aiosqlite
Required-by: bellows
```

**Hardware device info**
```
pi@raspberrypi:~ $ python3 ./elelabs-zigbee-ezsp-utility/Elelabs_EzspFwUtility.py probe --port=/dev/ttyAMA0
2021/02/06 16:12:56 Elelabs_EzspFwUtility:   Elelabs adapter detected:
2021/02/06 16:12:56 Elelabs_EzspFwUtility:   Adapter: ELR023
2021/02/06 16:12:56 Elelabs_EzspFwUtility:   Firmware: 6.0.3-64
2021/02/06 16:12:56 Elelabs_EzspFwUtility:   EZSP v6
```

**Bellows command errors**
```
pi@raspberrypi:~ $ bellows --device=/dev/ttyAMA0 scan

Traceback (most recent call last):
  File "/home/pi/ve/bin/bellows", line 10, in <module>
    sys.exit(main())
  File "/home/pi/ve/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/pi/ve/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/pi/ve/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/pi/ve/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/pi/ve/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/pi/ve/lib/python3.7/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/pi/ve/lib/python3.7/site-packages/bellows/cli/util.py", line 39, in inner
    loop.run_until_complete(f(*args, **kwargs))
  File "/usr/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
    return future.result()
  File "/home/pi/ve/lib/python3.7/site-packages/bellows/cli/network.py", line 141, in scan
    s = await util.setup(ctx.obj["device"], ctx.obj["baudrate"])
  File "/home/pi/ve/lib/python3.7/site-packages/bellows/cli/util.py", line 116, in setup
    await s.reset()
  File "/home/pi/ve/lib/python3.7/site-packages/bellows/ezsp/__init__.py", line 94, in reset
    await self._gw.reset()
  File "/home/pi/ve/lib/python3.7/site-packages/bellows/uart.py", line 218, in reset
    return await asyncio.wait_for(self._reset_future, timeout=RESET_TIMEOUT)
  File "/usr/lib/python3.7/asyncio/tasks.py", line 423, in wait_for
    raise futures.TimeoutError()
concurrent.futures._base.TimeoutError
```
**More**
```
pi@raspberrypi:~ $ bellows -d /dev/ttyAMA0 -v DEBUG form

debug: Using selector: EpollSelector
debug: executing functools.partial(<function connect.<locals>.connector at 0x75381a08>)
debug: operation functools.partial(<function connect.<locals>.connector at 0x75381a08>) completed
debug: executing functools.partial(<built-in method execute of sqlite3.Connection object at 0x7586fba0>, 'PRAGMA foreign_keys = ON', [])
debug: operation functools.partial(<built-in method execute of sqlite3.Connection object at 0x7586fba0>, 'PRAGMA foreign_keys = ON', []) completed
debug: executing functools.partial(<built-in method execute of sqlite3.Connection object at 0x7586fba0>, 'CREATE TABLE IF NOT EXISTS devices (ieee ieee, nwk, status)', [])
debug: operation functools.partial(<built-in method execute of sqlite3.Connection object at 0x7586fba0>, 'CREATE TABLE IF NOT EXISTS devices (ieee ieee, nwk, status)', []) completed
debug: executing functools.partial(<built-in method execute of sqlite3.Connection object at 0x7586fba0>, 'PRAGMA user_version = 3', [])
debug: operation functools.partial(<built-in method execute of sqlite3.Connection object at 0x7586fba0>, 'PRAGMA user_version = 3', []) completed
debug: executing functools.partial(<built-in method execute of sqlite3.Connection object at 0x7586fba0>, 'CREATE UNIQUE INDEX IF NOT EXISTS ieee_idx ON devices(ieee)', [])
debug: operation functools.partial(<built-in method execute of sqlite3.Connection object at 0x7586fba0>, 'CREATE UNIQUE INDEX IF NOT EXISTS ieee_idx ON devices(ieee)', []) completed
debug: executing functools.partial(<built-in method execute of sqlite3.Connection object at 0x7586fba0>, 'CREATE TABLE IF NOT EXISTS endpoints (ieee ieee, endpoint_id, profile_id, device_type device_type, status, FOREIGN KEY(ieee) REFERENCES devices(ieee) ON DELETE CASCADE)', [])
debug: operation functools.partial(<built-in method execute of sqlite3.Connection object at 0x7586fba0>, 'CREATE TABLE IF NOT EXISTS endpoints (ieee ieee, endpoint_id, profile_id, device_type device_type, status, FOREIGN KEY(ieee) REFERENCES devices(ieee) ON DELETE CASCADE)', []) completed
debug: executing functools.partial(<built-in method execute of sqlite3.Connection object at 0x7586fba0>, 'PRAGMA user_version = 3', [])
debug: operation functools.partial(<built-in method execute of sqlite3.Connection object at 0x7586fba0>, 'PRAGMA user_version = 3', []) completed
debug: executing functools.partial(<built-in method execute of sqlite3.Connection object at 0x7586fba0>, 'CREATE UNIQUE INDEX IF NOT EXISTS endpoint_idx ON endpoints(ieee, endpoint_id)', [])
debug: operation functools.partial(<built-in method execute of sqlite3.Connection object at 0x7586fba0>, 'CREATE UNIQUE INDEX IF NOT EXISTS endpoint_idx ON endpoints(ieee, endpoint_id)', []) completed
debug: executing functools.partial(<built-in method execute of sqlite3.Connection object at 0x7586fba0>, 'CREATE TABLE IF NOT EXISTS clusters (ieee ieee, endpoint_id, cluster, FOREIGN KEY(ieee, endpoint_id) REFERENCES endpoints(ieee, endpoint_id) ON DELETE CASCADE)', [])
debug: operation functools.partial(<built-in method execute of sqlite3.Connection object at 0x7586fba0>, 'CREATE TABLE IF NOT EXISTS clusters (ieee ieee, endpoint_id, cluster, FOREIGN KEY(ieee, endpoint_id) REFERENCES endpoints(ieee, endpoint_id) ON DELETE CASCADE)', []) completed
debug: executing functools.partial(<built-in method execute of sqlite3.Connection object at 0x7586fba0>, 'PRAGMA user_version = 3', [])
debug: operation functools.partial(<built-in method execute of sqlite3.Connection object at 0x7586fba0>, 'PRAGMA user_version = 3', []) completed
debug: executing functools.partial(<built-in method execute of sqlite3.Connection object at 0x7586fba0>, 'CREATE UNIQUE INDEX IF NOT EXISTS cluster_idx ON clusters(ieee, endpoint_id, cluster)', [])
debug: operation functools.partial(<built-in method execute of sqlite3.Connection object at 0x7586fba0>, 'CREATE UNIQUE INDEX IF NOT EXISTS cluster_idx ON clusters(ieee, endpoint_id, cluster)', []) completed
debug: executing functools.partial(<built-in method execute of sqlite3.Connection object at 0x7586fba0>, 'CREATE TABLE IF NOT EXISTS neighbors (device_ieee ieee NOT NULL, extended_pan_id ieee NOT NULL,ieee ieee NOT NULL, nwk INTEGER NOT NULL, struct INTEGER NOT NULL, permit_joining INTEGER NOT NULL, depth INTEGER NOT NULL, lqi INTEGER NOT NULL, FOREIGN KEY(device_ieee) REFERENCES devices(ieee) ON DELETE CASCADE)', [])
debug: operation functools.partial(<built-in method execute of sqlite3.Connection object at 0x7586fba0>, 'CREATE TABLE IF NOT EXISTS neighbors (device_ieee ieee NOT NULL, extended_pan_id ieee NOT NULL,ieee ieee NOT NULL, nwk INTEGER NOT NULL, struct INTEGER NOT NULL, permit_joining INTEGER NOT NULL, depth INTEGER NOT NULL, lqi INTEGER NOT NULL, FOREIGN KEY(device_ieee) REFERENCES devices(ieee) ON DELETE CASCADE)', []) completed
debug: executing functools.partial(<built-in method execute of sqlite3.Connection object at 0x7586fba0>, 'PRAGMA user_version = 3', [])
debug: operation functools.partial(<built-in method execute of sqlite3.Connection object at 0x7586fba0>, 'PRAGMA user_version = 3', []) completed
debug: executing functools.partial(<built-in method execute of sqlite3.Connection object at 0x7586fba0>, 'CREATE INDEX IF NOT EXISTS neighbors_idx ON neighbors(device_ieee)', [])
debug: operation functools.partial(<built-in method execute of sqlite3.Connection object at 0x7586fba0>, 'CREATE INDEX IF NOT EXISTS neighbors_idx ON neighbors(device_ieee)', []) completed
debug: executing functools.partial(<built-in method execute of sqlite3.Connection object at 0x7586fba0>, 'CREATE TABLE IF NOT EXISTS node_descriptors (ieee ieee, value, FOREIGN KEY(ieee) REFERENCES devices(ieee) ON DELETE CASCADE)', [])
debug: operation functools.partial(<built-in method execute of sqlite3.Connection object at 0x7586fba0>, 'CREATE TABLE IF NOT EXISTS node_descriptors (ieee ieee, value, FOREIGN KEY(ieee) REFERENCES devices(ieee) ON DELETE CASCADE)', []) completed
debug: executing functools.partial(<built-in method execute of sqlite3.Connection object at 0x7586fba0>, 'PRAGMA user_version = 3', [])
debug: operation functools.partial(<built-in method execute of sqlite3.Connection object at 0x7586fba0>, 'PRAGMA user_version = 3', []) completed
debug: executing functools.partial(<built-in method execute of sqlite3.Connection object at 0x7586fba0>, 'CREATE UNIQUE INDEX IF NOT EXISTS node_descriptors_idx ON node_descriptors(ieee)', [])
debug: operation functools.partial(<built-in method execute of sqlite3.Connection object at 0x7586fba0>, 'CREATE UNIQUE INDEX IF NOT EXISTS node_descriptors_idx ON node_descriptors(ieee)', []) completed
debug: executing functools.partial(<built-in method execute of sqlite3.Connection object at 0x7586fba0>, 'CREATE TABLE IF NOT EXISTS output_clusters (ieee ieee, endpoint_id, cluster, FOREIGN KEY(ieee, endpoint_id) REFERENCES endpoints(ieee, endpoint_id) ON DELETE CASCADE)', [])
debug: operation functools.partial(<built-in method execute of sqlite3.Connection object at 0x7586fba0>, 'CREATE TABLE IF NOT EXISTS output_clusters (ieee ieee, endpoint_id, cluster, FOREIGN KEY(ieee, endpoint_id) REFERENCES endpoints(ieee, endpoint_id) ON DELETE CASCADE)', []) completed
debug: executing functools.partial(<built-in method execute of sqlite3.Connection object at 0x7586fba0>, 'PRAGMA user_version = 3', [])
debug: operation functools.partial(<built-in method execute of sqlite3.Connection object at 0x7586fba0>, 'PRAGMA user_version = 3', []) completed
debug: executing functools.partial(<built-in method execute of sqlite3.Connection object at 0x7586fba0>, 'CREATE UNIQUE INDEX IF NOT EXISTS output_cluster_idx ON output_clusters(ieee, endpoint_id, cluster)', [])
debug: operation functools.partial(<built-in method execute of sqlite3.Connection object at 0x7586fba0>, 'CREATE UNIQUE INDEX IF NOT EXISTS output_cluster_idx ON output_clusters(ieee, endpoint_id, cluster)', []) completed
debug: executing functools.partial(<built-in method execute of sqlite3.Connection object at 0x7586fba0>, 'CREATE TABLE IF NOT EXISTS attributes (ieee ieee, endpoint_id, cluster, attrid, value, FOREIGN KEY(ieee) REFERENCES devices(ieee) ON DELETE CASCADE)', [])
debug: operation functools.partial(<built-in method execute of sqlite3.Connection object at 0x7586fba0>, 'CREATE TABLE IF NOT EXISTS attributes (ieee ieee, endpoint_id, cluster, attrid, value, FOREIGN KEY(ieee) REFERENCES devices(ieee) ON DELETE CASCADE)', []) completed
debug: executing functools.partial(<built-in method execute of sqlite3.Connection object at 0x7586fba0>, 'PRAGMA user_version = 3', [])
debug: operation functools.partial(<built-in method execute of sqlite3.Connection object at 0x7586fba0>, 'PRAGMA user_version = 3', []) completed
debug: executing functools.partial(<built-in method execute of sqlite3.Connection object at 0x7586fba0>, 'CREATE UNIQUE INDEX IF NOT EXISTS attribute_idx ON attributes(ieee, endpoint_id, cluster, attrid)', [])
debug: operation functools.partial(<built-in method execute of sqlite3.Connection object at 0x7586fba0>, 'CREATE UNIQUE INDEX IF NOT EXISTS attribute_idx ON attributes(ieee, endpoint_id, cluster, attrid)', []) completed
debug: executing functools.partial(<built-in method execute of sqlite3.Connection object at 0x7586fba0>, 'CREATE TABLE IF NOT EXISTS groups (group_id, name)', [])
debug: operation functools.partial(<built-in method execute of sqlite3.Connection object at 0x7586fba0>, 'CREATE TABLE IF NOT EXISTS groups (group_id, name)', []) completed
debug: executing functools.partial(<built-in method execute of sqlite3.Connection object at 0x7586fba0>, 'PRAGMA user_version = 3', [])
debug: operation functools.partial(<built-in method execute of sqlite3.Connection object at 0x7586fba0>, 'PRAGMA user_version = 3', []) completed
debug: executing functools.partial(<built-in method execute of sqlite3.Connection object at 0x7586fba0>, 'CREATE UNIQUE INDEX IF NOT EXISTS group_idx ON groups(group_id)', [])
debug: operation functools.partial(<built-in method execute of sqlite3.Connection object at 0x7586fba0>, 'CREATE UNIQUE INDEX IF NOT EXISTS group_idx ON groups(group_id)', []) completed
debug: executing functools.partial(<built-in method execute of sqlite3.Connection object at 0x7586fba0>, 'CREATE TABLE IF NOT EXISTS group_members (group_id, ieee ieee, endpoint_id,\n                FOREIGN KEY(group_id) REFERENCES groups(group_id) ON DELETE CASCADE,\n                FOREIGN KEY(ieee, endpoint_id)\n                REFERENCES endpoints(ieee, endpoint_id) ON DELETE CASCADE)', [])
debug: operation functools.partial(<built-in method execute of sqlite3.Connection object at 0x7586fba0>, 'CREATE TABLE IF NOT EXISTS group_members (group_id, ieee ieee, endpoint_id,\n                FOREIGN KEY(group_id) REFERENCES groups(group_id) ON DELETE CASCADE,\n                FOREIGN KEY(ieee, endpoint_id)\n                REFERENCES endpoints(ieee, endpoint_id) ON DELETE CASCADE)', []) completed
debug: executing functools.partial(<built-in method execute of sqlite3.Connection object at 0x7586fba0>, 'PRAGMA user_version = 3', [])
debug: operation functools.partial(<built-in method execute of sqlite3.Connection object at 0x7586fba0>, 'PRAGMA user_version = 3', []) completed
debug: executing functools.partial(<built-in method execute of sqlite3.Connection object at 0x7586fba0>, 'CREATE UNIQUE INDEX IF NOT EXISTS group_members_idx ON group_members(group_id, ieee, endpoint_id)', [])
debug: operation functools.partial(<built-in method execute of sqlite3.Connection object at 0x7586fba0>, 'CREATE UNIQUE INDEX IF NOT EXISTS group_members_idx ON group_members(group_id, ieee, endpoint_id)', []) completed
debug: executing functools.partial(<built-in method execute of sqlite3.Connection object at 0x7586fba0>, 'CREATE TABLE IF NOT EXISTS relays (ieee ieee, relays,\n                FOREIGN KEY(ieee) REFERENCES devices(ieee) ON DELETE CASCADE)', [])
debug: operation functools.partial(<built-in method execute of sqlite3.Connection object at 0x7586fba0>, 'CREATE TABLE IF NOT EXISTS relays (ieee ieee, relays,\n                FOREIGN KEY(ieee) REFERENCES devices(ieee) ON DELETE CASCADE)', []) completed
debug: executing functools.partial(<built-in method execute of sqlite3.Connection object at 0x7586fba0>, 'PRAGMA user_version = 3', [])
debug: operation functools.partial(<built-in method execute of sqlite3.Connection object at 0x7586fba0>, 'PRAGMA user_version = 3', []) completed
debug: executing functools.partial(<built-in method execute of sqlite3.Connection object at 0x7586fba0>, 'CREATE UNIQUE INDEX IF NOT EXISTS relays_idx ON relays(ieee)', [])
debug: operation functools.partial(<built-in method execute of sqlite3.Connection object at 0x7586fba0>, 'CREATE UNIQUE INDEX IF NOT EXISTS relays_idx ON relays(ieee)', []) completed
debug: executing functools.partial(<built-in method commit of sqlite3.Connection object at 0x7586fba0>)
debug: operation functools.partial(<built-in method commit of sqlite3.Connection object at 0x7586fba0>) completed
debug: Loading application state from %s
debug: executing functools.partial(<built-in method execute of sqlite3.Connection object at 0x7586fba0>, 'SELECT * FROM devices', [])
debug: operation functools.partial(<built-in method execute of sqlite3.Connection object at 0x7586fba0>, 'SELECT * FROM devices', []) completed
debug: executing functools.partial(<built-in method fetchmany of sqlite3.Cursor object at 0x7535dba0>, 64)
debug: operation functools.partial(<built-in method fetchmany of sqlite3.Cursor object at 0x7535dba0>, 64) completed
debug: executing functools.partial(<built-in method close of sqlite3.Cursor object at 0x7535dba0>)
debug: operation functools.partial(<built-in method close of sqlite3.Cursor object at 0x7535dba0>) completed
debug: executing functools.partial(<built-in method execute of sqlite3.Connection object at 0x7586fba0>, 'SELECT * FROM node_descriptors', [])
debug: operation functools.partial(<built-in method execute of sqlite3.Connection object at 0x7586fba0>, 'SELECT * FROM node_descriptors', []) completed
debug: executing functools.partial(<built-in method fetchmany of sqlite3.Cursor object at 0x7535dbe0>, 64)
debug: operation functools.partial(<built-in method fetchmany of sqlite3.Cursor object at 0x7535dbe0>, 64) completed
debug: executing functools.partial(<built-in method close of sqlite3.Cursor object at 0x7535dbe0>)
debug: operation functools.partial(<built-in method close of sqlite3.Cursor object at 0x7535dbe0>) completed
debug: executing functools.partial(<built-in method execute of sqlite3.Connection object at 0x7586fba0>, 'SELECT * FROM endpoints', [])
debug: operation functools.partial(<built-in method execute of sqlite3.Connection object at 0x7586fba0>, 'SELECT * FROM endpoints', []) completed
debug: executing functools.partial(<built-in method fetchmany of sqlite3.Cursor object at 0x7535dbe0>, 64)
debug: operation functools.partial(<built-in method fetchmany of sqlite3.Cursor object at 0x7535dbe0>, 64) completed
debug: executing functools.partial(<built-in method close of sqlite3.Cursor object at 0x7535dbe0>)
debug: operation functools.partial(<built-in method close of sqlite3.Cursor object at 0x7535dbe0>) completed
debug: executing functools.partial(<built-in method execute of sqlite3.Connection object at 0x7586fba0>, 'SELECT * FROM clusters', [])
debug: operation functools.partial(<built-in method execute of sqlite3.Connection object at 0x7586fba0>, 'SELECT * FROM clusters', []) completed
debug: executing functools.partial(<built-in method fetchmany of sqlite3.Cursor object at 0x7535dbe0>, 64)
debug: operation functools.partial(<built-in method fetchmany of sqlite3.Cursor object at 0x7535dbe0>, 64) completed
debug: executing functools.partial(<built-in method close of sqlite3.Cursor object at 0x7535dbe0>)
debug: operation functools.partial(<built-in method close of sqlite3.Cursor object at 0x7535dbe0>) completed
debug: executing functools.partial(<built-in method execute of sqlite3.Connection object at 0x7586fba0>, 'SELECT * FROM output_clusters', [])
debug: operation functools.partial(<built-in method execute of sqlite3.Connection object at 0x7586fba0>, 'SELECT * FROM output_clusters', []) completed
debug: executing functools.partial(<built-in method fetchmany of sqlite3.Cursor object at 0x7535dc20>, 64)
debug: operation functools.partial(<built-in method fetchmany of sqlite3.Cursor object at 0x7535dc20>, 64) completed
debug: executing functools.partial(<built-in method close of sqlite3.Cursor object at 0x7535dc20>)
debug: operation functools.partial(<built-in method close of sqlite3.Cursor object at 0x7535dc20>) completed
debug: executing functools.partial(<built-in method execute of sqlite3.Connection object at 0x7586fba0>, 'SELECT * FROM attributes WHERE attrid=4 OR attrid=5', [])
debug: operation functools.partial(<built-in method execute of sqlite3.Connection object at 0x7586fba0>, 'SELECT * FROM attributes WHERE attrid=4 OR attrid=5', []) completed
debug: executing functools.partial(<built-in method fetchmany of sqlite3.Cursor object at 0x7535dc20>, 64)
debug: operation functools.partial(<built-in method fetchmany of sqlite3.Cursor object at 0x7535dc20>, 64) completed
debug: executing functools.partial(<built-in method close of sqlite3.Cursor object at 0x7535dc20>)
debug: operation functools.partial(<built-in method close of sqlite3.Cursor object at 0x7535dc20>) completed
debug: executing functools.partial(<built-in method execute of sqlite3.Connection object at 0x7586fba0>, 'SELECT * FROM attributes', [])
debug: operation functools.partial(<built-in method execute of sqlite3.Connection object at 0x7586fba0>, 'SELECT * FROM attributes', []) completed
debug: executing functools.partial(<built-in method fetchmany of sqlite3.Cursor object at 0x7535dc20>, 64)
debug: operation functools.partial(<built-in method fetchmany of sqlite3.Cursor object at 0x7535dc20>, 64) completed
debug: executing functools.partial(<built-in method close of sqlite3.Cursor object at 0x7535dc20>)
debug: operation functools.partial(<built-in method close of sqlite3.Cursor object at 0x7535dc20>) completed
debug: executing functools.partial(<built-in method execute of sqlite3.Connection object at 0x7586fba0>, 'SELECT * FROM groups', [])
debug: operation functools.partial(<built-in method execute of sqlite3.Connection object at 0x7586fba0>, 'SELECT * FROM groups', []) completed
debug: executing functools.partial(<built-in method fetchmany of sqlite3.Cursor object at 0x7535dc20>, 64)
debug: operation functools.partial(<built-in method fetchmany of sqlite3.Cursor object at 0x7535dc20>, 64) completed
debug: executing functools.partial(<built-in method close of sqlite3.Cursor object at 0x7535dc20>)
debug: operation functools.partial(<built-in method close of sqlite3.Cursor object at 0x7535dc20>) completed
debug: executing functools.partial(<built-in method execute of sqlite3.Connection object at 0x7586fba0>, 'SELECT * FROM group_members', [])
debug: operation functools.partial(<built-in method execute of sqlite3.Connection object at 0x7586fba0>, 'SELECT * FROM group_members', []) completed
debug: executing functools.partial(<built-in method fetchmany of sqlite3.Cursor object at 0x7535dc20>, 64)
debug: operation functools.partial(<built-in method fetchmany of sqlite3.Cursor object at 0x7535dc20>, 64) completed
debug: executing functools.partial(<built-in method close of sqlite3.Cursor object at 0x7535dc20>)
debug: operation functools.partial(<built-in method close of sqlite3.Cursor object at 0x7535dc20>) completed
debug: executing functools.partial(<built-in method execute of sqlite3.Connection object at 0x7586fba0>, 'SELECT * FROM relays', [])
debug: operation functools.partial(<built-in method execute of sqlite3.Connection object at 0x7586fba0>, 'SELECT * FROM relays', []) completed
debug: executing functools.partial(<built-in method fetchmany of sqlite3.Cursor object at 0x7535dc20>, 64)
debug: operation functools.partial(<built-in method fetchmany of sqlite3.Cursor object at 0x7535dc20>, 64) completed
debug: executing functools.partial(<built-in method close of sqlite3.Cursor object at 0x7535dc20>)
debug: operation functools.partial(<built-in method close of sqlite3.Cursor object at 0x7535dc20>) completed
debug: executing functools.partial(<built-in method execute of sqlite3.Connection object at 0x7586fba0>, 'SELECT * FROM neighbors', [])
debug: operation functools.partial(<built-in method execute of sqlite3.Connection object at 0x7586fba0>, 'SELECT * FROM neighbors', []) completed
debug: executing functools.partial(<built-in method fetchmany of sqlite3.Cursor object at 0x7535dc20>, 64)
debug: operation functools.partial(<built-in method fetchmany of sqlite3.Cursor object at 0x7535dc20>, 64) completed
debug: executing functools.partial(<built-in method close of sqlite3.Cursor object at 0x7535dc20>)
debug: operation functools.partial(<built-in method close of sqlite3.Cursor object at 0x7535dc20>) completed
debug: Using selector: EpollSelector
debug: Resetting EZSP
debug: Resetting ASH
debug: Sending: b'1ac038bc7e'
Traceback (most recent call last):
  File "/home/pi/ve/bin/bellows", line 10, in <module>
    sys.exit(main())
  File "/home/pi/ve/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/pi/ve/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/pi/ve/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/pi/ve/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/pi/ve/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/pi/ve/lib/python3.7/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/pi/ve/lib/python3.7/site-packages/bellows/cli/application.py", line 45, in form
    return util.app(inner, app_startup=False, extra_config=extra_config)(ctx)
  File "/home/pi/ve/lib/python3.7/site-packages/bellows/cli/util.py", line 76, in inner
    loop.run_until_complete(async_inner(*args, **kwargs))
  File "/usr/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
    return future.result()
  File "/home/pi/ve/lib/python3.7/site-packages/bellows/cli/util.py", line 62, in async_inner
    await f(ctx, *args, **kwargs)
  File "/home/pi/ve/lib/python3.7/site-packages/bellows/cli/application.py", line 43, in inner
    await app.startup(auto_form=True)
  File "/home/pi/ve/lib/python3.7/site-packages/bellows/zigbee/application.py", line 108, in startup
    self._ezsp = await bellows.ezsp.EZSP.initialize(self.config)
  File "/home/pi/ve/lib/python3.7/site-packages/bellows/ezsp/__init__.py", line 79, in initialize
    await ezsp.reset()
  File "/home/pi/ve/lib/python3.7/site-packages/bellows/ezsp/__init__.py", line 94, in reset
    await self._gw.reset()
  File "/home/pi/ve/lib/python3.7/site-packages/bellows/uart.py", line 218, in reset
    return await asyncio.wait_for(self._reset_future, timeout=RESET_TIMEOUT)
  File "/usr/lib/python3.7/asyncio/tasks.py", line 423, in wait_for
    raise futures.TimeoutError()
concurrent.futures._base.TimeoutError
```

**Comment by Adminiuga** [comment]
elelabs is using 115200 baud rate by default, vs assumed 57600 used in bellows. Specify the baudrate in CLI

**Comment by jeffleary00** [comment]
Ah! thanks for the baud rate suggestion. 
That was it. Set it to 115200 and it works perfectly now.
Thank You!!
