### ISSUE TITLE
here after is an exemple of crash. What should I do to fix "ERROR_EXCEEDED_MAXIMUM_ACK_TIMEOUT_COUNT" ?

### ISSUE THREAD

**Issue by pipiche38** [zigpy/bellows#472]
here after is an exemple of crash. Should I do to fix "ERROR_EXCEEDED_MAXIMUM_ACK_TIMEOUT_COUNT" ?
And then it looks like everything is stuck, no more logs until we restart

```
2022-07-25 11:00:51,947 DEBUG   :Free buffers status EzspStatus.SUCCESS, value: 249
2022-07-25 11:00:51,948 DEBUG   :ezsp_counters: [MAC_RX_BROADCAST = 3934, MAC_TX_BROADCAST = 376, MAC_RX_UNICAST = 4365, MAC_TX_UNICAST_SUCCESS = 1867, MAC_TX_UNICAST_RETRY = 347, MAC_TX_UNICAST_FAILED = 130, APS_DATA_RX_BROADCAST = 25, APS_DATA_TX_BROADCAST = 19, APS_DATA_RX_UNICAST = 2568, APS_DATA_TX_UNICAST_SUCCESS = 235, APS_DATA_TX_UNICAST_RETRY = 79, APS_DATA_TX_UNICAST_FAILED = 34, ROUTE_DISCOVERY_INITIATED = 45, NEIGHBOR_ADDED = 199, NEIGHBOR_REMOVED = 183, NEIGHBOR_STALE = 129, JOIN_INDICATION = 0, CHILD_REMOVED = 0, ASH_OVERFLOW_ERROR = 0, ASH_FRAMING_ERROR = 0, ASH_OVERRUN_ERROR = 0, NWK_FRAME_COUNTER_FAILURE = 1, APS_FRAME_COUNTER_FAILURE = 0, UTILITY = 0, APS_LINK_KEY_NOT_AUTHORIZED = 0, NWK_DECRYPTION_FAILURE = 487, APS_DECRYPTION_FAILURE = 0, ALLOCATE_PACKET_BUFFER_FAILURE = 0, RELAYED_UNICAST = 0, PHY_TO_MAC_QUEUE_LIMIT_REACHED = 0, PACKET_VALIDATE_LIBRARY_DROPPED_COUNT = 0, TYPE_NWK_RETRY_OVERFLOW = 0, PHY_CCA_FAIL_COUNT = 129, BROADCAST_TABLE_FULL = 0, PTA_LO_PRI_REQUESTED = 0, PTA_HI_PRI_REQUESTED = 0, PTA_LO_PRI_DENIED = 0, PTA_HI_PRI_DENIED = 0, PTA_LO_PRI_TX_ABORTED = 0, PTA_HI_PRI_TX_ABORTED = 0, ADDRESS_CONFLICT_SENT = 0, EZSP_FREE_BUFFERS = 249]
2022-07-25 11:00:52,465 DEBUG   :Data frame: b'16a6b1a9112a15b658924a24ab5592499c3f5713a3ba9874face6e83fc7e2fa7e3eafb7e'
2022-07-25 11:00:52,466 DEBUG   :Sending: b'82503a7e'
2022-07-25 11:00:52,468 DEBUG   :Application frame 69 (incomingMessageHandler) received: b'00040106000101000000007170b84e74ffff07080d0a0000100008'
2022-07-25 11:00:52,470 DEBUG   :Received incomingMessageHandler frame with [<EmberIncomingMessageType.INCOMING_UNICAST: 0>, EmberApsFrame(profileId=260, clusterId=6, sourceEndpoint=1, destinationEndpoint=1, options=<EmberApsOption.APS_OPTION_NONE: 0>, groupId=0, sequence=113), 112, -72, 0x744e, 255, 255, b'\x08\r\n\x00\x00\x10\x00']
2022-07-25 11:00:53,445 DEBUG   :Data frame: b'26a6b1a9112a15b658954824ab1593499c2cd858c97a9874fade2383b97e0fa2efaf297e'
2022-07-25 11:00:53,446 DEBUG   :Sending: b'83401b7e'
2022-07-25 11:00:53,448 DEBUG   :Application frame 69 (incomingMessageHandler) received: b'000401010201014001000062fff324b4ffff0718400a4500300504'
2022-07-25 11:00:53,452 DEBUG   :Received incomingMessageHandler frame with [<EmberIncomingMessageType.INCOMING_UNICAST: 0>, EmberApsFrame(profileId=260, clusterId=513, sourceEndpoint=1, destinationEndpoint=1, options=<EmberApsOption.APS_OPTION_ENABLE_ROUTE_DISCOVERY|APS_OPTION_RETRY: 320>, groupId=0, sequence=98), 255, -13, 0xb424, 255, 255, b'\x18@\nE\x000\x05']
2022-07-25 11:00:53,463 DEBUG   :Data frame: b'36a6b1a9112a15b658954824ab1593499c2dd858c97a9874f4da5f98bd743f5afbccdaa73a7e'
2022-07-25 11:00:53,464 DEBUG   :Sending: b'8430fc7e'
2022-07-25 11:00:53,466 DEBUG   :Application frame 69 (incomingMessageHandler) received: b'000401010201014001000063fff324b4ffff091c3c11410a00fd100104'
2022-07-25 11:00:53,472 DEBUG   :Received incomingMessageHandler frame with [<EmberIncomingMessageType.INCOMING_UNICAST: 0>, EmberApsFrame(profileId=260, clusterId=513, sourceEndpoint=1, destinationEndpoint=1, options=<EmberApsOption.APS_OPTION_ENABLE_ROUTE_DISCOVERY|APS_OPTION_RETRY: 320>, groupId=0, sequence=99), 255, -13, 0xb424, 255, 255, b'\x1c<\x11A\n\x00\xfd\x10\x01']
2022-07-25 11:00:54,330 DEBUG   :Data frame: b'46a6b1a90d2a35e8ed889bdb5579f875048c273b787e'
2022-07-25 11:01:01,408 DEBUG   :Sending: b'8520dd7e'
2022-07-25 11:01:01,411 DEBUG   :Data frame: b'56a6b1a90d2a35e8ed889bdb5579f875048c270b257e'
2022-07-25 11:01:01,412 DEBUG   :Application frame 89 (incomingRouteRecordHandler) received: b'205ab41cd1feff2c6a3c98c200'
2022-07-25 11:01:01,413 DEBUG   :Sending: b'8610be7e'
2022-07-25 11:01:01,414 DEBUG   :Received incomingRouteRecordHandler frame with [0x5a20, 3c:6a:2c:ff:fe:d1:1c:b4, 152, -62, []]
2022-07-25 11:01:01,416 DEBUG   :Data frame: b'66a6b1a9112a15b658954824ab1593499c8abf69cd949874fade3583b97e0fa2e957c77e'
2022-07-25 11:01:01,417 DEBUG   :Processing route record request: (0x5a20, 3c:6a:2c:ff:fe:d1:1c:b4, 152, -62, [])
2022-07-25 11:01:01,418 DEBUG   :Sending: b'87009f7e'
2022-07-25 11:01:01,420 DEBUG   :Application frame 89 (incomingRouteRecordHandler) received: b'205ab41cd1feff2c6a3c98c200'
2022-07-25 11:01:01,421 DEBUG   :Data frame: b'76a6b1a9112a15b658954824ab1593499c8bbf69cd949874f4da5f98ab743f5afbccdc6cfc7e'
2022-07-25 11:01:01,422 DEBUG   :Received incomingRouteRecordHandler frame with [0x5a20, 3c:6a:2c:ff:fe:d1:1c:b4, 152, -62, []]
2022-07-25 11:01:01,423 DEBUG   :Sending: b'8070787e'
2022-07-25 11:01:01,424 DEBUG   :Processing route record request: (0x5a20, 3c:6a:2c:ff:fe:d1:1c:b4, 152, -62, [])
2022-07-25 11:01:01,426 DEBUG   :Data frame: b'4ea6b1a90d2a35e8ed889bdb5579f875048c27ab467e'
2022-07-25 11:01:01,428 DEBUG   :Application frame 69 (incomingMessageHandler) received: b'0004010102010140010000c498c2205affff0718560a4500300502'
2022-07-25 11:01:01,429 DEBUG   :Sending: b'8520dd7e'
2022-07-25 11:01:01,434 DEBUG   :Received incomingMessageHandler frame with [<EmberIncomingMessageType.INCOMING_UNICAST: 0>, EmberApsFrame(profileId=260, clusterId=513, sourceEndpoint=1, destinationEndpoint=1, options=<EmberApsOption.APS_OPTION_ENABLE_ROUTE_DISCOVERY|APS_OPTION_RETRY: 320>, groupId=0, sequence=196), 152, -62, 0x5a20, 255, 255, b'\x18V\nE\x000\x05']
2022-07-25 11:01:01,435 DEBUG   :Data frame: b'5ea6b1a90d2a35e8ed889bdb5579f875048c279b1b7e'
2022-07-25 11:01:01,445 DEBUG   :Sending: b'8610be7e'
2022-07-25 11:01:01,441 DEBUG   :Application frame 69 (incomingMessageHandler) received: b'0004010102010140010000c598c2205affff091c3c11570a00fd100102'
2022-07-25 11:01:01,457 DEBUG   :Received incomingMessageHandler frame with [<EmberIncomingMessageType.INCOMING_UNICAST: 0>, EmberApsFrame(profileId=260, clusterId=513, sourceEndpoint=1, destinationEndpoint=1, options=<EmberApsOption.APS_OPTION_ENABLE_ROUTE_DISCOVERY|APS_OPTION_RETRY: 320>, groupId=0, sequence=197), 152, -62, 0x5a20, 255, 255, b'\x1c<\x11W\n\x00\xfd\x10\x01']
2022-07-25 11:01:01,448 DEBUG   :Data frame: b'6ea6b1a9112a15b658954824ab1593499c8abf69cd949874fade3583b97e0fa2e979a37e'
2022-07-25 11:01:01,464 DEBUG   :Application frame 89 (incomingRouteRecordHandler) received: b'205ab41cd1feff2c6a3c98c200'
2022-07-25 11:01:01,464 DEBUG   :Sending: b'87009f7e'
2022-07-25 11:01:01,465 DEBUG   :Received incomingRouteRecordHandler frame with [0x5a20, 3c:6a:2c:ff:fe:d1:1c:b4, 152, -62, []]
2022-07-25 11:01:01,469 DEBUG   :Processing route record request: (0x5a20, 3c:6a:2c:ff:fe:d1:1c:b4, 152, -62, [])
2022-07-25 11:01:01,468 DEBUG   :Data frame: b'7ea6b1a9112a15b658954824ab1593499c8bbf69cd949874f4da5f98ab743f5afbccdc65377e'
2022-07-25 11:01:01,475 DEBUG   :Application frame 89 (incomingRouteRecordHandler) received: b'205ab41cd1feff2c6a3c98c200'
2022-07-25 11:01:01,477 DEBUG   :Sending: b'8070787e'
2022-07-25 11:01:01,480 DEBUG   :Received incomingRouteRecordHandler frame with [0x5a20, 3c:6a:2c:ff:fe:d1:1c:b4, 152, -62, []]
2022-07-25 11:01:01,481 DEBUG   :Data frame: b'4ea6b1a90d2a35e8ed889bdb5579f875048c27ab467e'
2022-07-25 11:01:01,484 DEBUG   :Processing route record request: (0x5a20, 3c:6a:2c:ff:fe:d1:1c:b4, 152, -62, [])
2022-07-25 11:01:01,485 DEBUG   :Sending: b'8520dd7e'
2022-07-25 11:01:01,486 DEBUG   :Application frame 69 (incomingMessageHandler) received: b'0004010102010140010000c498c2205affff0718560a4500300502'
2022-07-25 11:01:01,488 DEBUG   :Data frame: b'5ea6b1a90d2a35e8ed889bdb5579f875048c279b1b7e'
2022-07-25 11:01:01,493 DEBUG   :Received incomingMessageHandler frame with [<EmberIncomingMessageType.INCOMING_UNICAST: 0>, EmberApsFrame(profileId=260, clusterId=513, sourceEndpoint=1, destinationEndpoint=1, options=<EmberApsOption.APS_OPTION_ENABLE_ROUTE_DISCOVERY|APS_OPTION_RETRY: 320>, groupId=0, sequence=196), 152, -62, 0x5a20, 255, 255, b'\x18V\nE\x000\x05']
2022-07-25 11:01:01,494 DEBUG   :Sending: b'8610be7e'
2022-07-25 11:01:01,498 DEBUG   :Application frame 69 (incomingMessageHandler) received: b'0004010102010140010000c598c2205affff091c3c11570a00fd100102'
2022-07-25 11:01:01,500 DEBUG   :Data frame: b'6ea6b1a9112a15b658954824ab1593499c8abf69cd949874fade3583b97e0fa2e979a37e'
2022-07-25 11:01:01,505 DEBUG   :Received incomingMessageHandler frame with [<EmberIncomingMessageType.INCOMING_UNICAST: 0>, EmberApsFrame(profileId=260, clusterId=513, sourceEndpoint=1, destinationEndpoint=1, options=<EmberApsOption.APS_OPTION_ENABLE_ROUTE_DISCOVERY|APS_OPTION_RETRY: 320>, groupId=0, sequence=197), 152, -62, 0x5a20, 255, 255, b'\x1c<\x11W\n\x00\xfd\x10\x01']
2022-07-25 11:01:01,507 DEBUG   :Sending: b'87009f7e'
2022-07-25 11:01:01,510 DEBUG   :Application frame 89 (incomingRouteRecordHandler) received: b'205ab41cd1feff2c6a3c98c200'
2022-07-25 11:01:01,512 DEBUG   :Data frame: b'7ea6b1a9112a15b658954824ab1593499c8bbf69cd949874f4da5f98ab743f5afbccdc65377e'
2022-07-25 11:01:01,513 DEBUG   :Received incomingRouteRecordHandler frame with [0x5a20, 3c:6a:2c:ff:fe:d1:1c:b4, 152, -62, []]
2022-07-25 11:01:01,513 DEBUG   :Sending: b'8070787e'
2022-07-25 11:01:01,514 DEBUG   :Processing route record request: (0x5a20, 3c:6a:2c:ff:fe:d1:1c:b4, 152, -62, [])
2022-07-25 11:01:01,519 DEBUG   :Data frame: b'4ea6b1a90d2a35e8ed889bdb5579f875048c27ab467e'
2022-07-25 11:01:01,520 DEBUG   :Application frame 89 (incomingRouteRecordHandler) received: b'205ab41cd1feff2c6a3c98c200'
2022-07-25 11:01:01,521 DEBUG   :Sending: b'8520dd7e'
2022-07-25 11:01:01,522 DEBUG   :Received incomingRouteRecordHandler frame with [0x5a20, 3c:6a:2c:ff:fe:d1:1c:b4, 152, -62, []]
2022-07-25 11:01:01,524 DEBUG   :Data frame: b'5ea6b1a90d2a35e8ed889bdb5579f875048c279b1b7e'
2022-07-25 11:01:01,525 DEBUG   :Processing route record request: (0x5a20, 3c:6a:2c:ff:fe:d1:1c:b4, 152, -62, [])
2022-07-25 11:01:01,525 DEBUG   :Sending: b'8610be7e'
2022-07-25 11:01:01,527 DEBUG   :Application frame 69 (incomingMessageHandler) received: b'0004010102010140010000c498c2205affff0718560a4500300502'
2022-07-25 11:01:01,529 DEBUG   :Data frame: b'6ea6b1a9112a15b658954824ab1593499c8abf69cd949874fade3583b97e0fa2e979a37e'
2022-07-25 11:01:01,530 DEBUG   :Received incomingMessageHandler frame with [<EmberIncomingMessageType.INCOMING_UNICAST: 0>, EmberApsFrame(profileId=260, clusterId=513, sourceEndpoint=1, destinationEndpoint=1, options=<EmberApsOption.APS_OPTION_ENABLE_ROUTE_DISCOVERY|APS_OPTION_RETRY: 320>, groupId=0, sequence=196), 152, -62, 0x5a20, 255, 255, b'\x18V\nE\x000\x05']
2022-07-25 11:01:01,533 DEBUG   :Sending: b'87009f7e'
2022-07-25 11:01:01,535 DEBUG   :Application frame 69 (incomingMessageHandler) received: b'0004010102010140010000c598c2205affff091c3c11570a00fd100102'
2022-07-25 11:01:01,537 DEBUG   :Data frame: b'7ea6b1a9112a15b658954824ab1593499c8bbf69cd949874f4da5f98ab743f5afbccdc65377e'
2022-07-25 11:01:01,538 DEBUG   :Received incomingMessageHandler frame with [<EmberIncomingMessageType.INCOMING_UNICAST: 0>, EmberApsFrame(profileId=260, clusterId=513, sourceEndpoint=1, destinationEndpoint=1, options=<EmberApsOption.APS_OPTION_ENABLE_ROUTE_DISCOVERY|APS_OPTION_RETRY: 320>, groupId=0, sequence=197), 152, -62, 0x5a20, 255, 255, b'\x1c<\x11W\n\x00\xfd\x10\x01']
2022-07-25 11:01:01,540 DEBUG   :Sending: b'8070787e'
2022-07-25 11:01:01,543 DEBUG   :Application frame 89 (incomingRouteRecordHandler) received: b'205ab41cd1feff2c6a3c98c200'
2022-07-25 11:01:01,545 DEBUG   :Received incomingRouteRecordHandler frame with [0x5a20, 3c:6a:2c:ff:fe:d1:1c:b4, 152, -62, []]
2022-07-25 11:01:01,545 DEBUG   :Data frame: b'06a6b1a90d2a26f5bab99bdb5579f87563ab26dee553607e'
2022-07-25 11:01:01,546 DEBUG   :Processing route record request: (0x5a20, 3c:6a:2c:ff:fe:d1:1c:b4, 152, -62, [])
2022-07-25 11:01:01,550 DEBUG   :Sending: b'8160597e'
2022-07-25 11:01:01,552 DEBUG   :Application frame 89 (incomingRouteRecordHandler) received: b'205ab41cd1feff2c6a3c98c200'
2022-07-25 11:01:01,553 DEBUG   :Error code: ERROR_EXCEEDED_MAXIMUM_ACK_TIMEOUT_COUNT, Version: 2, frame: b'c20251a8bd7e'
2022-07-25 11:01:01,553 DEBUG   :Received incomingRouteRecordHandler frame with [0x5a20, 3c:6a:2c:ff:fe:d1:1c:b4, 152, -62, []]
2022-07-25 11:01:01,555 DEBUG   :Processing route record request: (0x5a20, 3c:6a:2c:ff:fe:d1:1c:b4, 152, -62, [])
2022-07-25 11:01:01,556 DEBUG   :Application frame 69 (incomingMessageHandler) received: b'0004010102010140010000c498c2205affff0718560a4500300502'
2022-07-25 11:01:01,558 DEBUG   :Received incomingMessageHandler frame with [<EmberIncomingMessageType.INCOMING_UNICAST: 0>, EmberApsFrame(profileId=260, clusterId=513, sourceEndpoint=1, destinationEndpoint=1, options=<EmberApsOption.APS_OPTION_ENABLE_ROUTE_DISCOVERY|APS_OPTION_RETRY: 320>, groupId=0, sequence=196), 152, -62, 0x5a20, 255, 255, b'\x18V\nE\x000\x05']
2022-07-25 11:01:01,563 DEBUG   :Application frame 69 (incomingMessageHandler) received: b'0004010102010140010000c598c2205affff091c3c11570a00fd100102'
2022-07-25 11:01:01,565 DEBUG   :Received incomingMessageHandler frame with [<EmberIncomingMessageType.INCOMING_UNICAST: 0>, EmberApsFrame(profileId=260, clusterId=513, sourceEndpoint=1, destinationEndpoint=1, options=<EmberApsOption.APS_OPTION_ENABLE_ROUTE_DISCOVERY|APS_OPTION_RETRY: 320>, groupId=0, sequence=197), 152, -62, 0x5a20, 255, 255, b'\x1c<\x11W\n\x00\xfd\x10\x01']
2022-07-25 11:01:01,566 DEBUG   :Error code: ERROR_EXCEEDED_MAXIMUM_ACK_TIMEOUT_COUNT, Version: 2, frame: b'c20251a8bd7e'
2022-07-25 11:01:01,572 DEBUG   :Application frame 89 (incomingRouteRecordHandler) received: b'3347e32dd1feff2c6a3cffe5017508'
2022-07-25 11:01:01,574 DEBUG   :Error code: ERROR_EXCEEDED_MAXIMUM_ACK_TIMEOUT_COUNT, Version: 2, frame: b'c20251a8bd7e'
2022-07-25 11:01:01,575 DEBUG   :Received incomingRouteRecordHandler frame with [0x4733, 3c:6a:2c:ff:fe:d1:2d:e3, 255, -27, [0x0875]]
2022-07-25 11:01:01,579 DEBUG   :Processing route record request: (0x4733, 3c:6a:2c:ff:fe:d1:2d:e3, 255, -27, [0x0875])
2022-07-25 11:01:01,580 ERROR   :NCP entered failed state. Requesting APP controller restart
2022-07-25 11:01:01,582 DEBUG   :Received _reset_controller_application frame with (<NcpResetCode.ERROR_EXCEEDED_MAXIMUM_ACK_TIMEOUT_COUNT: 81>,)
2022-07-25 11:01:01,583 DEBUG   :Resetting ControllerApplication. Cause: 'NcpResetCode.ERROR_EXCEEDED_MAXIMUM_ACK_TIMEOUT_COUNT'
2022-07-25 11:01:01,584 DEBUG   :Closed serial connection
2022-07-25 11:01:01,585 ERROR   :NCP entered failed state. Requesting APP controller restart
2022-07-25 11:01:01,587 DEBUG   :Received _reset_controller_application frame with (<NcpResetCode.ERROR_EXCEEDED_MAXIMUM_ACK_TIMEOUT_COUNT: 81>,)
2022-07-25 11:01:01,587 DEBUG   :Resetting ControllerApplication. Cause: 'NcpResetCode.ERROR_EXCEEDED_MAXIMUM_ACK_TIMEOUT_COUNT'
2022-07-25 11:01:01,588 DEBUG   :Preempting ControllerApplication reset
2022-07-25 11:01:01,588 ERROR   :NCP entered failed state. Requesting APP controller restart
2022-07-25 11:01:01,589 DEBUG   :Received _reset_controller_application frame with (<NcpResetCode.ERROR_EXCEEDED_MAXIMUM_ACK_TIMEOUT_COUNT: 81>,)
2022-07-25 11:01:01,592 DEBUG   :Resetting ControllerApplication. Cause: 'NcpResetCode.ERROR_EXCEEDED_MAXIMUM_ACK_TIMEOUT_COUNT'
2022-07-25 11:01:01,593 DEBUG   :Preempting ControllerApplication reset
2022-07-25 11:04:16,693 ERROR   :Task exception was never retrieved
future: <Task finished coro=<transport_request() done, defined at /home/pi/domoticz/plugins/Domoticz-Zigbee/Classes/ZigpyTransport/zigpyThread.py:575> exception=ControllerError('ApplicationController is not running')>
Traceback (most recent call last):
  File "/home/pi/domoticz/plugins/Domoticz-Zigbee/Classes/ZigpyTransport/zigpyThread.py", line 595, in transport_request
    result, msg = await self.app.request( destination, Profile, Cluster, sEp, dEp, sequence, payload, expect_reply, use_ieee )
  File "/home/pi/domoticz/plugins/Domoticz-Zigbee/bellows/zigbee/application.py", line 727, in request
    raise ControllerError("ApplicationController is not running")
bellows.exception.ControllerError: ApplicationController is not running
2022-07-25 11:04:16,729 ERROR   :Task exception was never retrieved
future: <Task finished coro=<transport_request() done, defined at /home/pi/domoticz/plugins/Domoticz-Zigbee/Classes/ZigpyTransport/zigpyThread.py:575> exception=ControllerError('ApplicationController is not running')>
Traceback (most recent call last):
  File "/home/pi/domoticz/plugins/Domoticz-Zigbee/Classes/ZigpyTransport/zigpyThread.py", line 595, in transport_request
    result, msg = await self.app.request( destination, Profile, Cluster, sEp, dEp, sequence, payload, expect_reply, use_ieee )
  File "/home/pi/domoticz/plugins/Domoticz-Zigbee/bellows/zigbee/application.py", line 727, in request
    raise ControllerError("ApplicationController is not running")
bellows.exception.ControllerError: ApplicationController is not running
2022-07-25 11:04:16,730 ERROR   :Task exception was never retrieved
future: <Task finished coro=<transport_request() done, defined at /home/pi/domoticz/plugins/Domoticz-Zigbee/Classes/ZigpyTransport/zigpyThread.py:575> exception=ControllerError('ApplicationController is not running')>
Traceback (most recent call last):
  File "/home/pi/domoticz/plugins/Domoticz-Zigbee/Classes/ZigpyTransport/zigpyThread.py", line 595, in transport_request
    result, msg = await self.app.request( destination, Profile, Cluster, sEp, dEp, sequence, payload, expect_reply, use_ieee )
  File "/home/pi/domoticz/plugins/Domoticz-Zigbee/bellows/zigbee/application.py", line 727, in request
    raise ControllerError("ApplicationController is not running")
bellows.exception.ControllerError: ApplicationController is not running
```

```
pi@CasaiaProV4-test:~/domoticz/plugins/Domoticz-Zigbee$ bellows -d /dev/ttyAMA0 -b 115200 info
[60:a4:23:ff:fe:aa:33:ac]
[0x0000]
[<EmberNetworkStatus.JOINED_NETWORK: 2>]
[<EmberStatus.SUCCESS: 0>, <EmberNodeType.COORDINATOR: 1>, EmberNetworkParameters(extendedPanId=79:a7:ee:a4:e1:b3:a6:bf, panId=0xfaa2, radioTxPower=8, radioChannel=15, joinMethod=<EmberJoinMethod.USE_MAC_ASSOCIATION: 0>, nwkManagerId=0x0000, nwkUpdateId=0, channels=<Channels.ALL_CHANNELS: 134215680>)]
[<EmberStatus.SUCCESS: 0>, EmberCurrentSecurityState(bitmask=<EmberCurrentSecurityBitmask.TRUST_CENTER_USES_HASHED_LINK_KEY|64|32|HAVE_TRUST_CENTER_LINK_KEY|GLOBAL_LINK_KEY: 244>, trustCenterLongAddress=60:a4:23:ff:fe:aa:33:ac)]
Manufacturer: Elelabs
Board name: ELR023
EmberZNet version: 6.10.3.0 build 297
```

_Originally posted by @pipiche38 in https://github.com/zigpy/bellows/issues/419#issuecomment-1193778910_

**Comment by pipiche38** [comment]
just to keep it open (before a bot close it)
