### ISSUE TITLE
Error doing job: Exception in callback ThreadsafeProxy

### ISSUE THREAD

**Issue by Yardco** [zigpy/bellows#618]
(Hoping I'm creating the issue in the right place, if not, please direct me to the correct repo.)
Since testing out home assistant beta 2024.5, I'm getting the following error:

```
Logger: homeassistant
Source: /usr/src/homeassistant/homeassistant/runner.py:147
First occurred: 08:55:34 (39 occurrences)
Last logged: 09:14:19

Error doing job: Exception in callback ThreadsafeProxy.__getattr__.<locals>.func_wrapper.<locals>.check_result_wrapper() at /usr/local/lib/python3.12/site-packages/bellows/thread.py:110
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.12/site-packages/bellows/thread.py", line 111, in check_result_wrapper
    result = call()
             ^^^^^^
  File "/usr/local/lib/python3.12/site-packages/bellows/ezsp/__init__.py", line 330, in frame_received
    self._protocol(data)
  File "/usr/local/lib/python3.12/site-packages/bellows/ezsp/protocol.py", line 103, in __call__
    result, data = self.types.deserialize(data, schema)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/bellows/types/__init__.py", line 9, in deserialize
    value, data = type_.deserialize(data)
                  ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/zigpy/types/basic.py", line 197, in deserialize
    raise ValueError(f"Data is too short to contain {byte_size} bytes")
ValueError: Data is too short to contain 2 bytes
```

This error is accompanied by the following warning:

```
Logger: bellows.ezsp.protocol
Source: runner.py:190
First occurred: 08:55:34 (39 occurrences)
Last logged: 09:14:19

Failed to parse frame changeSourceRouteHandler: b'0c6f15'
Failed to parse frame changeSourceRouteHandler: b'0c4794'
Failed to parse frame changeSourceRouteHandler: b'0ccc82'
```

turned on debug mode and captured the following log from startup: https://dpaste.org/h98Kv

**Comment by puddly** [comment]
Could you enable debug mode for the ZHA integration and reload it?

**Comment by Yardco** [comment]
Sure thing (added the log directly here, struggeling with adding it to dpaste)
[log file](https://github.com/zigpy/bellows/files/15149925/home-assistant_zha_2024-04-29T13-32-55.233Z.log)
