### ISSUE TITLE
Error trying to pair thermostat devices (st218)

### ISSUE THREAD

**Issue by titilambert** [zigpy/bellows#76]
Hello,

I got devices paired, but I wanted to retry the pairing.
So I stopped my Home assistant, delete zigbee.db file et restart Home assistant.
Now When I try to pair devices I got that
```
ov 16 13:16:51 androlapin hass[24814]: 2017-11-16 13:16:51 WARNING (MainThread) [bellows.zigbee.zdo] [0xe895:zdo] Unsupported ZDO request 0x0036
Nov 16 13:16:51 androlapin hass[24814]: 2017-11-16 13:16:51 WARNING (MainThread) [bellows.zigbee.zdo] [0xe895:zdo] Unsupported ZDO request 0x0036
Nov 16 13:16:51 androlapin hass[24814]: 2017-11-16 13:16:51 WARNING (MainThread) [bellows.zigbee.zdo] [0xe895:zdo] Unsupported ZDO request 0x0036
Nov 16 13:16:51 androlapin hass[24814]: 2017-11-16 13:16:51 ERROR (MainThread) [homeassistant.core] Timer got out of sync. Resetting
Nov 16 13:17:28 androlapin hass[24814]: 2017-11-16 13:17:28 ERROR (MainThread) [homeassistant.core] Timer got out of sync. Resetting
Nov 16 13:18:28 androlapin hass[24814]: 2017-11-16 13:18:28 ERROR (MainThread) [homeassistant.core] Error doing job: Exception in callback SerialTransport._read_ready()
Nov 16 13:18:28 androlapin hass[24814]: Traceback (most recent call last):
Nov 16 13:18:28 androlapin hass[24814]:   File "/usr/lib/python3.6/asyncio/events.py", line 127, in _run
Nov 16 13:18:28 androlapin hass[24814]:     self._callback(*self._args)
Nov 16 13:18:28 androlapin hass[24814]:   File "/opt/homeassistant/deps/lib/python3.6/site-packages/serial_asyncio/__init__.py", line 106, in _read_ready
Nov 16 13:18:28 androlapin hass[24814]:     self._protocol.data_received(data)
Nov 16 13:18:28 androlapin hass[24814]:   File "/opt/homeassistant/deps/lib/python3.6/site-packages/bellows/uart.py", line 61, in data_received
Nov 16 13:18:28 androlapin hass[24814]:     self.frame_received(frame)
Nov 16 13:18:28 androlapin hass[24814]:   File "/opt/homeassistant/deps/lib/python3.6/site-packages/bellows/uart.py", line 81, in frame_received
Nov 16 13:18:28 androlapin hass[24814]:     self.rstack_frame_received(data)
Nov 16 13:18:28 androlapin hass[24814]:   File "/opt/homeassistant/deps/lib/python3.6/site-packages/bellows/uart.py", line 128, in rstack_frame_received
Nov 16 13:18:28 androlapin hass[24814]:     self._reset_future.set_result(True)
Nov 16 13:18:28 androlapin hass[24814]:   File "/usr/lib/python3.6/asyncio/futures.py", line 300, in set_result
Nov 16 13:18:28 androlapin hass[24814]:     raise InvalidStateError('{}: {!r}'.format(self._state, self))
Nov 16 13:18:28 androlapin hass[24814]: asyncio.base_futures.InvalidStateError: FINISHED: <Future finished result=True>
Nov 16 13:18:40 androlapin hass[24814]: 2017-11-16 13:18:40 ERROR (MainThread) [homeassistant.core] Error doing job: Exception in callback SerialTransport._read_ready()
Nov 16 13:18:40 androlapin hass[24814]: Traceback (most recent call last):
Nov 16 13:18:40 androlapin hass[24814]:   File "/usr/lib/python3.6/asyncio/events.py", line 127, in _run
Nov 16 13:18:40 androlapin hass[24814]:     self._callback(*self._args)
Nov 16 13:18:40 androlapin hass[24814]:   File "/opt/homeassistant/deps/lib/python3.6/site-packages/serial_asyncio/__init__.py", line 106, in _read_ready
Nov 16 13:18:40 androlapin hass[24814]:     self._protocol.data_received(data)
Nov 16 13:18:40 androlapin hass[24814]:   File "/opt/homeassistant/deps/lib/python3.6/site-packages/bellows/uart.py", line 61, in data_received
Nov 16 13:18:40 androlapin hass[24814]:     self.frame_received(frame)
Nov 16 13:18:40 androlapin hass[24814]:   File "/opt/homeassistant/deps/lib/python3.6/site-packages/bellows/uart.py", line 81, in frame_received
Nov 16 13:18:40 androlapin hass[24814]:     self.rstack_frame_received(data)
Nov 16 13:18:40 androlapin hass[24814]:   File "/opt/homeassistant/deps/lib/python3.6/site-packages/bellows/uart.py", line 128, in rstack_frame_received
Nov 16 13:18:40 androlapin hass[24814]:     self._reset_future.set_result(True)
Nov 16 13:18:40 androlapin hass[24814]:   File "/usr/lib/python3.6/asyncio/futures.py", line 300, in set_result
Nov 16 13:18:40 androlapin hass[24814]:     raise InvalidStateError('{}: {!r}'.format(self._state, self))
Nov 16 13:18:40 androlapin hass[24814]: asyncio.base_futures.InvalidStateError: FINISHED: <Future finished result=True>
```

**Comment by Adminiuga** [comment]
Fixed in #101
